<?xml version="1.0" encoding="utf-8"?><Database Name="CarBoyAuthenticationDB" Class="DataAccessDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=CarBoyAuthenticationDB;Persist Security Info=True;User ID=." SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CarBoyAuthenticationDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.sessionTbl" Member="sessionTbls">
    <Type Name="sessionTbl">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="sessionID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="authKeyID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="diffKey" Type="System.String" DbType="NVarChar(55) NOT NULL" CanBeNull="false" />
      <Column Name="messageIdCollection" Type="System.String" DbType="NVarChar(800) NOT NULL" CanBeNull="false" />
      <Column Name="forgetRetry" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="regDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.settingTbl" Member="settingTbls">
    <Type Name="settingTbl">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="value" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.smsTbl" Member="smsTbls">
    <Type Name="smsTbl">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="hash" Type="System.String" DbType="Char(40) NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="regDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="retry" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="floodTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="retryCheck" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>