//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarBoyWebservice.smsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://gamavas.ir/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBoolean", Namespace="http://gamavas.ir/", ItemName="boolean")]
    [System.SerializableAttribute()]
    public class ArrayOfBoolean : System.Collections.Generic.List<bool> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSendIn", Namespace="http://gamavas.ir/")]
    [System.SerializableAttribute()]
    public partial class DataSendIn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellphoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private bool FarsiField;
        
        private bool FlashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UDHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ShortCode {
            get {
                return this.ShortCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortCodeField, value) != true)) {
                    this.ShortCodeField = value;
                    this.RaisePropertyChanged("ShortCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Cellphone {
            get {
                return this.CellphoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CellphoneField, value) != true)) {
                    this.CellphoneField = value;
                    this.RaisePropertyChanged("Cellphone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Farsi {
            get {
                return this.FarsiField;
            }
            set {
                if ((this.FarsiField.Equals(value) != true)) {
                    this.FarsiField = value;
                    this.RaisePropertyChanged("Farsi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Flash {
            get {
                return this.FlashField;
            }
            set {
                if ((this.FlashField.Equals(value) != true)) {
                    this.FlashField = value;
                    this.RaisePropertyChanged("Flash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string UDH {
            get {
                return this.UDHField;
            }
            set {
                if ((object.ReferenceEquals(this.UDHField, value) != true)) {
                    this.UDHField = value;
                    this.RaisePropertyChanged("UDH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ServiceID {
            get {
                return this.ServiceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceIDField, value) != true)) {
                    this.ServiceIDField = value;
                    this.RaisePropertyChanged("ServiceID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSendOut", Namespace="http://gamavas.ir/")]
    [System.SerializableAttribute()]
    public partial class DataSendOut : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long ClientIDField;
        
        private long ServerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long ServerID {
            get {
                return this.ServerIDField;
            }
            set {
                if ((this.ServerIDField.Equals(value) != true)) {
                    this.ServerIDField = value;
                    this.RaisePropertyChanged("ServerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageReceive", Namespace="http://gamavas.ir/")]
    [System.SerializableAttribute()]
    public partial class MessageReceive : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long RowIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UDHField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long RowID {
            get {
                return this.RowIDField;
            }
            set {
                if ((this.RowIDField.Equals(value) != true)) {
                    this.RowIDField = value;
                    this.RaisePropertyChanged("RowID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DateTimeField, value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Receiver {
            get {
                return this.ReceiverField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverField, value) != true)) {
                    this.ReceiverField = value;
                    this.RaisePropertyChanged("Receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string UDH {
            get {
                return this.UDHField;
            }
            set {
                if ((object.ReferenceEquals(this.UDHField, value) != true)) {
                    this.UDHField = value;
                    this.RaisePropertyChanged("UDH");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gamavas.ir/", ConfigurationName="smsService.smsSoap")]
    public interface smsSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/HelloWorld", ReplyAction="*")]
        CarBoyWebservice.smsService.HelloWorldResponse HelloWorld(CarBoyWebservice.smsService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.HelloWorldResponse> HelloWorldAsync(CarBoyWebservice.smsService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doGetInfo", ReplyAction="*")]
        CarBoyWebservice.smsService.doGetInfoResponse doGetInfo(CarBoyWebservice.smsService.doGetInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doGetInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.doGetInfoResponse> doGetInfoAsync(CarBoyWebservice.smsService.doGetInfoRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doSendSMS", ReplyAction="*")]
        CarBoyWebservice.smsService.doSendSMSResponse doSendSMS(CarBoyWebservice.smsService.doSendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doSendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.doSendSMSResponse> doSendSMSAsync(CarBoyWebservice.smsService.doSendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doSendArraySMS", ReplyAction="*")]
        CarBoyWebservice.smsService.doSendArraySMSResponse doSendArraySMS(CarBoyWebservice.smsService.doSendArraySMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doSendArraySMS", ReplyAction="*")]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.doSendArraySMSResponse> doSendArraySMSAsync(CarBoyWebservice.smsService.doSendArraySMSRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doSendSMSArrayC", ReplyAction="*")]
        CarBoyWebservice.smsService.doSendSMSArrayCResponse doSendSMSArrayC(CarBoyWebservice.smsService.doSendSMSArrayCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doSendSMSArrayC", ReplyAction="*")]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.doSendSMSArrayCResponse> doSendSMSArrayCAsync(CarBoyWebservice.smsService.doSendSMSArrayCRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doCheckClientID", ReplyAction="*")]
        CarBoyWebservice.smsService.doCheckClientIDResponse doCheckClientID(CarBoyWebservice.smsService.doCheckClientIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doCheckClientID", ReplyAction="*")]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.doCheckClientIDResponse> doCheckClientIDAsync(CarBoyWebservice.smsService.doCheckClientIDRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doGetDelivery", ReplyAction="*")]
        CarBoyWebservice.smsService.doGetDeliveryResponse doGetDelivery(CarBoyWebservice.smsService.doGetDeliveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doGetDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.doGetDeliveryResponse> doGetDeliveryAsync(CarBoyWebservice.smsService.doGetDeliveryRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doGetDeliveryOlder", ReplyAction="*")]
        CarBoyWebservice.smsService.doGetDeliveryOlderResponse doGetDeliveryOlder(CarBoyWebservice.smsService.doGetDeliveryOlderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doGetDeliveryOlder", ReplyAction="*")]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.doGetDeliveryOlderResponse> doGetDeliveryOlderAsync(CarBoyWebservice.smsService.doGetDeliveryOlderRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doReceiveSMS", ReplyAction="*")]
        CarBoyWebservice.smsService.doReceiveSMSResponse doReceiveSMS(CarBoyWebservice.smsService.doReceiveSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doReceiveSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.doReceiveSMSResponse> doReceiveSMSAsync(CarBoyWebservice.smsService.doReceiveSMSRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doReceiveSMSArray", ReplyAction="*")]
        CarBoyWebservice.smsService.doReceiveSMSArrayResponse doReceiveSMSArray(CarBoyWebservice.smsService.doReceiveSMSArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doReceiveSMSArray", ReplyAction="*")]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.doReceiveSMSArrayResponse> doReceiveSMSArrayAsync(CarBoyWebservice.smsService.doReceiveSMSArrayRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/getInfoXML", ReplyAction="*")]
        CarBoyWebservice.smsService.getInfoXMLResponse getInfoXML(CarBoyWebservice.smsService.getInfoXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/getInfoXML", ReplyAction="*")]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.getInfoXMLResponse> getInfoXMLAsync(CarBoyWebservice.smsService.getInfoXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(CarBoyWebservice.smsService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(CarBoyWebservice.smsService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doGetInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doGetInfo", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.doGetInfoRequestBody Body;
        
        public doGetInfoRequest() {
        }
        
        public doGetInfoRequest(CarBoyWebservice.smsService.doGetInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class doGetInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        public doGetInfoRequestBody() {
        }
        
        public doGetInfoRequestBody(string uUsername, string uPassword) {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doGetInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doGetInfoResponse", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.doGetInfoResponseBody Body;
        
        public doGetInfoResponse() {
        }
        
        public doGetInfoResponse(CarBoyWebservice.smsService.doGetInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class doGetInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doGetInfoResult;
        
        public doGetInfoResponseBody() {
        }
        
        public doGetInfoResponseBody(string doGetInfoResult) {
            this.doGetInfoResult = doGetInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendSMS", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.doSendSMSRequestBody Body;
        
        public doSendSMSRequest() {
        }
        
        public doSendSMSRequest(CarBoyWebservice.smsService.doSendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class doSendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string uNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string uCellphones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string uMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool uFarsi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool uTopic;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool uFlash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string uUDH;
        
        public doSendSMSRequestBody() {
        }
        
        public doSendSMSRequestBody(string uUsername, string uPassword, string uNumber, string uCellphones, string uMessage, bool uFarsi, bool uTopic, bool uFlash, string uUDH) {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uNumber = uNumber;
            this.uCellphones = uCellphones;
            this.uMessage = uMessage;
            this.uFarsi = uFarsi;
            this.uTopic = uTopic;
            this.uFlash = uFlash;
            this.uUDH = uUDH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendSMSResponse", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.doSendSMSResponseBody Body;
        
        public doSendSMSResponse() {
        }
        
        public doSendSMSResponse(CarBoyWebservice.smsService.doSendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class doSendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doSendSMSResult;
        
        public doSendSMSResponseBody() {
        }
        
        public doSendSMSResponseBody(string doSendSMSResult) {
            this.doSendSMSResult = doSendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendArraySMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendArraySMS", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.doSendArraySMSRequestBody Body;
        
        public doSendArraySMSRequest() {
        }
        
        public doSendArraySMSRequest(CarBoyWebservice.smsService.doSendArraySMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class doSendArraySMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CarBoyWebservice.smsService.ArrayOfString uNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public CarBoyWebservice.smsService.ArrayOfString uCellphone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public CarBoyWebservice.smsService.ArrayOfString uMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public CarBoyWebservice.smsService.ArrayOfBoolean uFarsi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public CarBoyWebservice.smsService.ArrayOfBoolean uTopic;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public CarBoyWebservice.smsService.ArrayOfBoolean uFlash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public CarBoyWebservice.smsService.ArrayOfString uUDH;
        
        public doSendArraySMSRequestBody() {
        }
        
        public doSendArraySMSRequestBody(string uUsername, string uPassword, CarBoyWebservice.smsService.ArrayOfString uNumber, CarBoyWebservice.smsService.ArrayOfString uCellphone, CarBoyWebservice.smsService.ArrayOfString uMessage, CarBoyWebservice.smsService.ArrayOfBoolean uFarsi, CarBoyWebservice.smsService.ArrayOfBoolean uTopic, CarBoyWebservice.smsService.ArrayOfBoolean uFlash, CarBoyWebservice.smsService.ArrayOfString uUDH) {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uNumber = uNumber;
            this.uCellphone = uCellphone;
            this.uMessage = uMessage;
            this.uFarsi = uFarsi;
            this.uTopic = uTopic;
            this.uFlash = uFlash;
            this.uUDH = uUDH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendArraySMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendArraySMSResponse", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.doSendArraySMSResponseBody Body;
        
        public doSendArraySMSResponse() {
        }
        
        public doSendArraySMSResponse(CarBoyWebservice.smsService.doSendArraySMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class doSendArraySMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doSendArraySMSResult;
        
        public doSendArraySMSResponseBody() {
        }
        
        public doSendArraySMSResponseBody(string doSendArraySMSResult) {
            this.doSendArraySMSResult = doSendArraySMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendSMSArrayCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendSMSArrayC", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.doSendSMSArrayCRequestBody Body;
        
        public doSendSMSArrayCRequest() {
        }
        
        public doSendSMSArrayCRequest(CarBoyWebservice.smsService.doSendSMSArrayCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class doSendSMSArrayCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CarBoyWebservice.smsService.DataSendIn[] uDataSendIn;
        
        public doSendSMSArrayCRequestBody() {
        }
        
        public doSendSMSArrayCRequestBody(string uUsername, string uPassword, CarBoyWebservice.smsService.DataSendIn[] uDataSendIn) {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uDataSendIn = uDataSendIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendSMSArrayCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendSMSArrayCResponse", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.doSendSMSArrayCResponseBody Body;
        
        public doSendSMSArrayCResponse() {
        }
        
        public doSendSMSArrayCResponse(CarBoyWebservice.smsService.doSendSMSArrayCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class doSendSMSArrayCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarBoyWebservice.smsService.DataSendOut[] doSendSMSArrayCResult;
        
        public doSendSMSArrayCResponseBody() {
        }
        
        public doSendSMSArrayCResponseBody(CarBoyWebservice.smsService.DataSendOut[] doSendSMSArrayCResult) {
            this.doSendSMSArrayCResult = doSendSMSArrayCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doCheckClientIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doCheckClientID", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.doCheckClientIDRequestBody Body;
        
        public doCheckClientIDRequest() {
        }
        
        public doCheckClientIDRequest(CarBoyWebservice.smsService.doCheckClientIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class doCheckClientIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uClientIDs;
        
        public doCheckClientIDRequestBody() {
        }
        
        public doCheckClientIDRequestBody(string uUsername, string uClientIDs) {
            this.uUsername = uUsername;
            this.uClientIDs = uClientIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doCheckClientIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doCheckClientIDResponse", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.doCheckClientIDResponseBody Body;
        
        public doCheckClientIDResponse() {
        }
        
        public doCheckClientIDResponse(CarBoyWebservice.smsService.doCheckClientIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class doCheckClientIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doCheckClientIDResult;
        
        public doCheckClientIDResponseBody() {
        }
        
        public doCheckClientIDResponseBody(string doCheckClientIDResult) {
            this.doCheckClientIDResult = doCheckClientIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doGetDeliveryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doGetDelivery", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.doGetDeliveryRequestBody Body;
        
        public doGetDeliveryRequest() {
        }
        
        public doGetDeliveryRequest(CarBoyWebservice.smsService.doGetDeliveryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class doGetDeliveryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uReturnIDs;
        
        public doGetDeliveryRequestBody() {
        }
        
        public doGetDeliveryRequestBody(string uUsername, string uReturnIDs) {
            this.uUsername = uUsername;
            this.uReturnIDs = uReturnIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doGetDeliveryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doGetDeliveryResponse", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.doGetDeliveryResponseBody Body;
        
        public doGetDeliveryResponse() {
        }
        
        public doGetDeliveryResponse(CarBoyWebservice.smsService.doGetDeliveryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class doGetDeliveryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doGetDeliveryResult;
        
        public doGetDeliveryResponseBody() {
        }
        
        public doGetDeliveryResponseBody(string doGetDeliveryResult) {
            this.doGetDeliveryResult = doGetDeliveryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doGetDeliveryOlderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doGetDeliveryOlder", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.doGetDeliveryOlderRequestBody Body;
        
        public doGetDeliveryOlderRequest() {
        }
        
        public doGetDeliveryOlderRequest(CarBoyWebservice.smsService.doGetDeliveryOlderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class doGetDeliveryOlderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uReturnIDs;
        
        public doGetDeliveryOlderRequestBody() {
        }
        
        public doGetDeliveryOlderRequestBody(string uUsername, string uReturnIDs) {
            this.uUsername = uUsername;
            this.uReturnIDs = uReturnIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doGetDeliveryOlderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doGetDeliveryOlderResponse", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.doGetDeliveryOlderResponseBody Body;
        
        public doGetDeliveryOlderResponse() {
        }
        
        public doGetDeliveryOlderResponse(CarBoyWebservice.smsService.doGetDeliveryOlderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class doGetDeliveryOlderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doGetDeliveryOlderResult;
        
        public doGetDeliveryOlderResponseBody() {
        }
        
        public doGetDeliveryOlderResponseBody(string doGetDeliveryOlderResult) {
            this.doGetDeliveryOlderResult = doGetDeliveryOlderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doReceiveSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doReceiveSMS", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.doReceiveSMSRequestBody Body;
        
        public doReceiveSMSRequest() {
        }
        
        public doReceiveSMSRequest(CarBoyWebservice.smsService.doReceiveSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class doReceiveSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long uLastRowID;
        
        public doReceiveSMSRequestBody() {
        }
        
        public doReceiveSMSRequestBody(string uUsername, string uPassword, long uLastRowID) {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uLastRowID = uLastRowID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doReceiveSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doReceiveSMSResponse", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.doReceiveSMSResponseBody Body;
        
        public doReceiveSMSResponse() {
        }
        
        public doReceiveSMSResponse(CarBoyWebservice.smsService.doReceiveSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class doReceiveSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doReceiveSMSResult;
        
        public doReceiveSMSResponseBody() {
        }
        
        public doReceiveSMSResponseBody(string doReceiveSMSResult) {
            this.doReceiveSMSResult = doReceiveSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doReceiveSMSArrayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doReceiveSMSArray", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.doReceiveSMSArrayRequestBody Body;
        
        public doReceiveSMSArrayRequest() {
        }
        
        public doReceiveSMSArrayRequest(CarBoyWebservice.smsService.doReceiveSMSArrayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class doReceiveSMSArrayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long uLastRowID;
        
        public doReceiveSMSArrayRequestBody() {
        }
        
        public doReceiveSMSArrayRequestBody(string uUsername, string uPassword, long uLastRowID) {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uLastRowID = uLastRowID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doReceiveSMSArrayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doReceiveSMSArrayResponse", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.doReceiveSMSArrayResponseBody Body;
        
        public doReceiveSMSArrayResponse() {
        }
        
        public doReceiveSMSArrayResponse(CarBoyWebservice.smsService.doReceiveSMSArrayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class doReceiveSMSArrayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarBoyWebservice.smsService.MessageReceive[] doReceiveSMSArrayResult;
        
        public doReceiveSMSArrayResponseBody() {
        }
        
        public doReceiveSMSArrayResponseBody(CarBoyWebservice.smsService.MessageReceive[] doReceiveSMSArrayResult) {
            this.doReceiveSMSArrayResult = doReceiveSMSArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInfoXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfoXML", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.getInfoXMLRequestBody Body;
        
        public getInfoXMLRequest() {
        }
        
        public getInfoXMLRequest(CarBoyWebservice.smsService.getInfoXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class getInfoXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        public getInfoXMLRequestBody() {
        }
        
        public getInfoXMLRequestBody(string uUsername, string uPassword) {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInfoXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfoXMLResponse", Namespace="http://gamavas.ir/", Order=0)]
        public CarBoyWebservice.smsService.getInfoXMLResponseBody Body;
        
        public getInfoXMLResponse() {
        }
        
        public getInfoXMLResponse(CarBoyWebservice.smsService.getInfoXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gamavas.ir/")]
    public partial class getInfoXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getInfoXMLResult;
        
        public getInfoXMLResponseBody() {
        }
        
        public getInfoXMLResponseBody(string getInfoXMLResult) {
            this.getInfoXMLResult = getInfoXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface smsSoapChannel : CarBoyWebservice.smsService.smsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class smsSoapClient : System.ServiceModel.ClientBase<CarBoyWebservice.smsService.smsSoap>, CarBoyWebservice.smsService.smsSoap {
        
        public smsSoapClient() {
        }
        
        public smsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public smsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarBoyWebservice.smsService.HelloWorldResponse CarBoyWebservice.smsService.smsSoap.HelloWorld(CarBoyWebservice.smsService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            CarBoyWebservice.smsService.HelloWorldRequest inValue = new CarBoyWebservice.smsService.HelloWorldRequest();
            inValue.Body = new CarBoyWebservice.smsService.HelloWorldRequestBody();
            CarBoyWebservice.smsService.HelloWorldResponse retVal = ((CarBoyWebservice.smsService.smsSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.HelloWorldResponse> CarBoyWebservice.smsService.smsSoap.HelloWorldAsync(CarBoyWebservice.smsService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarBoyWebservice.smsService.HelloWorldResponse> HelloWorldAsync() {
            CarBoyWebservice.smsService.HelloWorldRequest inValue = new CarBoyWebservice.smsService.HelloWorldRequest();
            inValue.Body = new CarBoyWebservice.smsService.HelloWorldRequestBody();
            return ((CarBoyWebservice.smsService.smsSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarBoyWebservice.smsService.doGetInfoResponse CarBoyWebservice.smsService.smsSoap.doGetInfo(CarBoyWebservice.smsService.doGetInfoRequest request) {
            return base.Channel.doGetInfo(request);
        }
        
        public string doGetInfo(string uUsername, string uPassword) {
            CarBoyWebservice.smsService.doGetInfoRequest inValue = new CarBoyWebservice.smsService.doGetInfoRequest();
            inValue.Body = new CarBoyWebservice.smsService.doGetInfoRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            CarBoyWebservice.smsService.doGetInfoResponse retVal = ((CarBoyWebservice.smsService.smsSoap)(this)).doGetInfo(inValue);
            return retVal.Body.doGetInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.doGetInfoResponse> CarBoyWebservice.smsService.smsSoap.doGetInfoAsync(CarBoyWebservice.smsService.doGetInfoRequest request) {
            return base.Channel.doGetInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarBoyWebservice.smsService.doGetInfoResponse> doGetInfoAsync(string uUsername, string uPassword) {
            CarBoyWebservice.smsService.doGetInfoRequest inValue = new CarBoyWebservice.smsService.doGetInfoRequest();
            inValue.Body = new CarBoyWebservice.smsService.doGetInfoRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            return ((CarBoyWebservice.smsService.smsSoap)(this)).doGetInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarBoyWebservice.smsService.doSendSMSResponse CarBoyWebservice.smsService.smsSoap.doSendSMS(CarBoyWebservice.smsService.doSendSMSRequest request) {
            return base.Channel.doSendSMS(request);
        }
        
        public string doSendSMS(string uUsername, string uPassword, string uNumber, string uCellphones, string uMessage, bool uFarsi, bool uTopic, bool uFlash, string uUDH) {
            CarBoyWebservice.smsService.doSendSMSRequest inValue = new CarBoyWebservice.smsService.doSendSMSRequest();
            inValue.Body = new CarBoyWebservice.smsService.doSendSMSRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uNumber = uNumber;
            inValue.Body.uCellphones = uCellphones;
            inValue.Body.uMessage = uMessage;
            inValue.Body.uFarsi = uFarsi;
            inValue.Body.uTopic = uTopic;
            inValue.Body.uFlash = uFlash;
            inValue.Body.uUDH = uUDH;
            CarBoyWebservice.smsService.doSendSMSResponse retVal = ((CarBoyWebservice.smsService.smsSoap)(this)).doSendSMS(inValue);
            return retVal.Body.doSendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.doSendSMSResponse> CarBoyWebservice.smsService.smsSoap.doSendSMSAsync(CarBoyWebservice.smsService.doSendSMSRequest request) {
            return base.Channel.doSendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarBoyWebservice.smsService.doSendSMSResponse> doSendSMSAsync(string uUsername, string uPassword, string uNumber, string uCellphones, string uMessage, bool uFarsi, bool uTopic, bool uFlash, string uUDH) {
            CarBoyWebservice.smsService.doSendSMSRequest inValue = new CarBoyWebservice.smsService.doSendSMSRequest();
            inValue.Body = new CarBoyWebservice.smsService.doSendSMSRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uNumber = uNumber;
            inValue.Body.uCellphones = uCellphones;
            inValue.Body.uMessage = uMessage;
            inValue.Body.uFarsi = uFarsi;
            inValue.Body.uTopic = uTopic;
            inValue.Body.uFlash = uFlash;
            inValue.Body.uUDH = uUDH;
            return ((CarBoyWebservice.smsService.smsSoap)(this)).doSendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarBoyWebservice.smsService.doSendArraySMSResponse CarBoyWebservice.smsService.smsSoap.doSendArraySMS(CarBoyWebservice.smsService.doSendArraySMSRequest request) {
            return base.Channel.doSendArraySMS(request);
        }
        
        public string doSendArraySMS(string uUsername, string uPassword, CarBoyWebservice.smsService.ArrayOfString uNumber, CarBoyWebservice.smsService.ArrayOfString uCellphone, CarBoyWebservice.smsService.ArrayOfString uMessage, CarBoyWebservice.smsService.ArrayOfBoolean uFarsi, CarBoyWebservice.smsService.ArrayOfBoolean uTopic, CarBoyWebservice.smsService.ArrayOfBoolean uFlash, CarBoyWebservice.smsService.ArrayOfString uUDH) {
            CarBoyWebservice.smsService.doSendArraySMSRequest inValue = new CarBoyWebservice.smsService.doSendArraySMSRequest();
            inValue.Body = new CarBoyWebservice.smsService.doSendArraySMSRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uNumber = uNumber;
            inValue.Body.uCellphone = uCellphone;
            inValue.Body.uMessage = uMessage;
            inValue.Body.uFarsi = uFarsi;
            inValue.Body.uTopic = uTopic;
            inValue.Body.uFlash = uFlash;
            inValue.Body.uUDH = uUDH;
            CarBoyWebservice.smsService.doSendArraySMSResponse retVal = ((CarBoyWebservice.smsService.smsSoap)(this)).doSendArraySMS(inValue);
            return retVal.Body.doSendArraySMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.doSendArraySMSResponse> CarBoyWebservice.smsService.smsSoap.doSendArraySMSAsync(CarBoyWebservice.smsService.doSendArraySMSRequest request) {
            return base.Channel.doSendArraySMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarBoyWebservice.smsService.doSendArraySMSResponse> doSendArraySMSAsync(string uUsername, string uPassword, CarBoyWebservice.smsService.ArrayOfString uNumber, CarBoyWebservice.smsService.ArrayOfString uCellphone, CarBoyWebservice.smsService.ArrayOfString uMessage, CarBoyWebservice.smsService.ArrayOfBoolean uFarsi, CarBoyWebservice.smsService.ArrayOfBoolean uTopic, CarBoyWebservice.smsService.ArrayOfBoolean uFlash, CarBoyWebservice.smsService.ArrayOfString uUDH) {
            CarBoyWebservice.smsService.doSendArraySMSRequest inValue = new CarBoyWebservice.smsService.doSendArraySMSRequest();
            inValue.Body = new CarBoyWebservice.smsService.doSendArraySMSRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uNumber = uNumber;
            inValue.Body.uCellphone = uCellphone;
            inValue.Body.uMessage = uMessage;
            inValue.Body.uFarsi = uFarsi;
            inValue.Body.uTopic = uTopic;
            inValue.Body.uFlash = uFlash;
            inValue.Body.uUDH = uUDH;
            return ((CarBoyWebservice.smsService.smsSoap)(this)).doSendArraySMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarBoyWebservice.smsService.doSendSMSArrayCResponse CarBoyWebservice.smsService.smsSoap.doSendSMSArrayC(CarBoyWebservice.smsService.doSendSMSArrayCRequest request) {
            return base.Channel.doSendSMSArrayC(request);
        }
        
        public CarBoyWebservice.smsService.DataSendOut[] doSendSMSArrayC(string uUsername, string uPassword, CarBoyWebservice.smsService.DataSendIn[] uDataSendIn) {
            CarBoyWebservice.smsService.doSendSMSArrayCRequest inValue = new CarBoyWebservice.smsService.doSendSMSArrayCRequest();
            inValue.Body = new CarBoyWebservice.smsService.doSendSMSArrayCRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uDataSendIn = uDataSendIn;
            CarBoyWebservice.smsService.doSendSMSArrayCResponse retVal = ((CarBoyWebservice.smsService.smsSoap)(this)).doSendSMSArrayC(inValue);
            return retVal.Body.doSendSMSArrayCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.doSendSMSArrayCResponse> CarBoyWebservice.smsService.smsSoap.doSendSMSArrayCAsync(CarBoyWebservice.smsService.doSendSMSArrayCRequest request) {
            return base.Channel.doSendSMSArrayCAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarBoyWebservice.smsService.doSendSMSArrayCResponse> doSendSMSArrayCAsync(string uUsername, string uPassword, CarBoyWebservice.smsService.DataSendIn[] uDataSendIn) {
            CarBoyWebservice.smsService.doSendSMSArrayCRequest inValue = new CarBoyWebservice.smsService.doSendSMSArrayCRequest();
            inValue.Body = new CarBoyWebservice.smsService.doSendSMSArrayCRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uDataSendIn = uDataSendIn;
            return ((CarBoyWebservice.smsService.smsSoap)(this)).doSendSMSArrayCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarBoyWebservice.smsService.doCheckClientIDResponse CarBoyWebservice.smsService.smsSoap.doCheckClientID(CarBoyWebservice.smsService.doCheckClientIDRequest request) {
            return base.Channel.doCheckClientID(request);
        }
        
        public string doCheckClientID(string uUsername, string uClientIDs) {
            CarBoyWebservice.smsService.doCheckClientIDRequest inValue = new CarBoyWebservice.smsService.doCheckClientIDRequest();
            inValue.Body = new CarBoyWebservice.smsService.doCheckClientIDRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uClientIDs = uClientIDs;
            CarBoyWebservice.smsService.doCheckClientIDResponse retVal = ((CarBoyWebservice.smsService.smsSoap)(this)).doCheckClientID(inValue);
            return retVal.Body.doCheckClientIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.doCheckClientIDResponse> CarBoyWebservice.smsService.smsSoap.doCheckClientIDAsync(CarBoyWebservice.smsService.doCheckClientIDRequest request) {
            return base.Channel.doCheckClientIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarBoyWebservice.smsService.doCheckClientIDResponse> doCheckClientIDAsync(string uUsername, string uClientIDs) {
            CarBoyWebservice.smsService.doCheckClientIDRequest inValue = new CarBoyWebservice.smsService.doCheckClientIDRequest();
            inValue.Body = new CarBoyWebservice.smsService.doCheckClientIDRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uClientIDs = uClientIDs;
            return ((CarBoyWebservice.smsService.smsSoap)(this)).doCheckClientIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarBoyWebservice.smsService.doGetDeliveryResponse CarBoyWebservice.smsService.smsSoap.doGetDelivery(CarBoyWebservice.smsService.doGetDeliveryRequest request) {
            return base.Channel.doGetDelivery(request);
        }
        
        public string doGetDelivery(string uUsername, string uReturnIDs) {
            CarBoyWebservice.smsService.doGetDeliveryRequest inValue = new CarBoyWebservice.smsService.doGetDeliveryRequest();
            inValue.Body = new CarBoyWebservice.smsService.doGetDeliveryRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uReturnIDs = uReturnIDs;
            CarBoyWebservice.smsService.doGetDeliveryResponse retVal = ((CarBoyWebservice.smsService.smsSoap)(this)).doGetDelivery(inValue);
            return retVal.Body.doGetDeliveryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.doGetDeliveryResponse> CarBoyWebservice.smsService.smsSoap.doGetDeliveryAsync(CarBoyWebservice.smsService.doGetDeliveryRequest request) {
            return base.Channel.doGetDeliveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarBoyWebservice.smsService.doGetDeliveryResponse> doGetDeliveryAsync(string uUsername, string uReturnIDs) {
            CarBoyWebservice.smsService.doGetDeliveryRequest inValue = new CarBoyWebservice.smsService.doGetDeliveryRequest();
            inValue.Body = new CarBoyWebservice.smsService.doGetDeliveryRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uReturnIDs = uReturnIDs;
            return ((CarBoyWebservice.smsService.smsSoap)(this)).doGetDeliveryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarBoyWebservice.smsService.doGetDeliveryOlderResponse CarBoyWebservice.smsService.smsSoap.doGetDeliveryOlder(CarBoyWebservice.smsService.doGetDeliveryOlderRequest request) {
            return base.Channel.doGetDeliveryOlder(request);
        }
        
        public string doGetDeliveryOlder(string uUsername, string uReturnIDs) {
            CarBoyWebservice.smsService.doGetDeliveryOlderRequest inValue = new CarBoyWebservice.smsService.doGetDeliveryOlderRequest();
            inValue.Body = new CarBoyWebservice.smsService.doGetDeliveryOlderRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uReturnIDs = uReturnIDs;
            CarBoyWebservice.smsService.doGetDeliveryOlderResponse retVal = ((CarBoyWebservice.smsService.smsSoap)(this)).doGetDeliveryOlder(inValue);
            return retVal.Body.doGetDeliveryOlderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.doGetDeliveryOlderResponse> CarBoyWebservice.smsService.smsSoap.doGetDeliveryOlderAsync(CarBoyWebservice.smsService.doGetDeliveryOlderRequest request) {
            return base.Channel.doGetDeliveryOlderAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarBoyWebservice.smsService.doGetDeliveryOlderResponse> doGetDeliveryOlderAsync(string uUsername, string uReturnIDs) {
            CarBoyWebservice.smsService.doGetDeliveryOlderRequest inValue = new CarBoyWebservice.smsService.doGetDeliveryOlderRequest();
            inValue.Body = new CarBoyWebservice.smsService.doGetDeliveryOlderRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uReturnIDs = uReturnIDs;
            return ((CarBoyWebservice.smsService.smsSoap)(this)).doGetDeliveryOlderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarBoyWebservice.smsService.doReceiveSMSResponse CarBoyWebservice.smsService.smsSoap.doReceiveSMS(CarBoyWebservice.smsService.doReceiveSMSRequest request) {
            return base.Channel.doReceiveSMS(request);
        }
        
        public string doReceiveSMS(string uUsername, string uPassword, long uLastRowID) {
            CarBoyWebservice.smsService.doReceiveSMSRequest inValue = new CarBoyWebservice.smsService.doReceiveSMSRequest();
            inValue.Body = new CarBoyWebservice.smsService.doReceiveSMSRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uLastRowID = uLastRowID;
            CarBoyWebservice.smsService.doReceiveSMSResponse retVal = ((CarBoyWebservice.smsService.smsSoap)(this)).doReceiveSMS(inValue);
            return retVal.Body.doReceiveSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.doReceiveSMSResponse> CarBoyWebservice.smsService.smsSoap.doReceiveSMSAsync(CarBoyWebservice.smsService.doReceiveSMSRequest request) {
            return base.Channel.doReceiveSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarBoyWebservice.smsService.doReceiveSMSResponse> doReceiveSMSAsync(string uUsername, string uPassword, long uLastRowID) {
            CarBoyWebservice.smsService.doReceiveSMSRequest inValue = new CarBoyWebservice.smsService.doReceiveSMSRequest();
            inValue.Body = new CarBoyWebservice.smsService.doReceiveSMSRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uLastRowID = uLastRowID;
            return ((CarBoyWebservice.smsService.smsSoap)(this)).doReceiveSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarBoyWebservice.smsService.doReceiveSMSArrayResponse CarBoyWebservice.smsService.smsSoap.doReceiveSMSArray(CarBoyWebservice.smsService.doReceiveSMSArrayRequest request) {
            return base.Channel.doReceiveSMSArray(request);
        }
        
        public CarBoyWebservice.smsService.MessageReceive[] doReceiveSMSArray(string uUsername, string uPassword, long uLastRowID) {
            CarBoyWebservice.smsService.doReceiveSMSArrayRequest inValue = new CarBoyWebservice.smsService.doReceiveSMSArrayRequest();
            inValue.Body = new CarBoyWebservice.smsService.doReceiveSMSArrayRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uLastRowID = uLastRowID;
            CarBoyWebservice.smsService.doReceiveSMSArrayResponse retVal = ((CarBoyWebservice.smsService.smsSoap)(this)).doReceiveSMSArray(inValue);
            return retVal.Body.doReceiveSMSArrayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.doReceiveSMSArrayResponse> CarBoyWebservice.smsService.smsSoap.doReceiveSMSArrayAsync(CarBoyWebservice.smsService.doReceiveSMSArrayRequest request) {
            return base.Channel.doReceiveSMSArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarBoyWebservice.smsService.doReceiveSMSArrayResponse> doReceiveSMSArrayAsync(string uUsername, string uPassword, long uLastRowID) {
            CarBoyWebservice.smsService.doReceiveSMSArrayRequest inValue = new CarBoyWebservice.smsService.doReceiveSMSArrayRequest();
            inValue.Body = new CarBoyWebservice.smsService.doReceiveSMSArrayRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uLastRowID = uLastRowID;
            return ((CarBoyWebservice.smsService.smsSoap)(this)).doReceiveSMSArrayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarBoyWebservice.smsService.getInfoXMLResponse CarBoyWebservice.smsService.smsSoap.getInfoXML(CarBoyWebservice.smsService.getInfoXMLRequest request) {
            return base.Channel.getInfoXML(request);
        }
        
        public string getInfoXML(string uUsername, string uPassword) {
            CarBoyWebservice.smsService.getInfoXMLRequest inValue = new CarBoyWebservice.smsService.getInfoXMLRequest();
            inValue.Body = new CarBoyWebservice.smsService.getInfoXMLRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            CarBoyWebservice.smsService.getInfoXMLResponse retVal = ((CarBoyWebservice.smsService.smsSoap)(this)).getInfoXML(inValue);
            return retVal.Body.getInfoXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarBoyWebservice.smsService.getInfoXMLResponse> CarBoyWebservice.smsService.smsSoap.getInfoXMLAsync(CarBoyWebservice.smsService.getInfoXMLRequest request) {
            return base.Channel.getInfoXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarBoyWebservice.smsService.getInfoXMLResponse> getInfoXMLAsync(string uUsername, string uPassword) {
            CarBoyWebservice.smsService.getInfoXMLRequest inValue = new CarBoyWebservice.smsService.getInfoXMLRequest();
            inValue.Body = new CarBoyWebservice.smsService.getInfoXMLRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            return ((CarBoyWebservice.smsService.smsSoap)(this)).getInfoXMLAsync(inValue);
        }
    }
}
